version: '3.5'

services:

  ravendb:
    container_name: marketplace-ch9-ravendb
    image: ravendb/ravendb
    ports:
      - 8080:8080
    environment:
      - RAVEN_ARGS="--config-path=/opt/RavenDB/config/settings.default.json"
    volumes:
      - c:/DockerVolumes/RavenDB/config:/opt/RavenDB/config
      - c:/DockerVolumes/RavenDB/data:/var/lib/ravendb/
