version: '3.5'

services:

  eventstore:
    container_name: marketplace-eventstore
    image: eventstore/eventstore
    ports:
        - 2113:2113
        - 1112:1112
        - 1113:1113
    environment:
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_LOG=/var/log/eventstore
      - EVENTSTORE_DB=/var/data/eventstore
    volumes:
      - c:/DockerVolumes/eventstore/data:/var/data/eventstore
      - c:/DockerVolumes/eventstore/logs:/var/log/eventstore
   